# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /mlflow

# Install MLflow and other dependencies
RUN pip install --no-cache-dir \
    mlflow==2.20.2 scikit-learn==1.6.1 pymysql==1.1.0

# Create the directory for MLflow artifacts
RUN mkdir -p /mlflow/artifacts

# Expose the MLflow UI port
EXPOSE 5000

# Command to run the MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow/artifacts"]
