{
 "title": "EFD Training Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# EFD Dashboard\n## Training Metrics\n### Polynomial Regression Model"
   }
  },
  {
   "title": "Avg. Training Metrics",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(v1_train_mse)", "legendFormat": "MSE" },
    { "expr": "avg(v1_train_rmse)", "legendFormat": "RMSE" },
    { "expr": "avg(v1_train_mae)", "legendFormat": "MAE" },
    { "expr": "avg(v1_train_r2)", "legendFormat": "R2" },
    { "expr": "avg(v1_train_adj_r2)", "legendFormat": "ADJ. R2 " }
   ]
  },
  {
   "title": "Avg. Testing Metrics",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(v1_test_mse)", "legendFormat": "MSE" },
    { "expr": "avg(v1_test_rmse)", "legendFormat": "RMSE" },
    { "expr": "avg(v1_test_mae)", "legendFormat": "MAE" },
    { "expr": "avg(v1_test_r2)", "legendFormat": "R2" },
    { "expr": "avg(v1_test_adj_r2)", "legendFormat": "ADJ. R2" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 }, "options": { "content": "### Decision Tree Model" } },
  {
   "title": "Avg. Training Metrics",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(v2_train_mse)", "legendFormat": "MSE" },
    { "expr": "avg(v2_train_rmse)", "legendFormat": "RMSE" },
    { "expr": "avg(v2_train_mae)", "legendFormat": "MAE" },
    { "expr": "avg(v2_train_r2)", "legendFormat": "R2" },
    { "expr": "avg(v2_train_adj_r2)", "legendFormat": "ADJ. R2" }
   ]
  },
  {
   "title": "Avg. Testing Metrics",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(v2_test_mse)", "legendFormat": "MSE" },
    { "expr": "v2_test_rmse", "legendFormat": "RMSE" },
    { "expr": "avg(v2_test_mae)", "legendFormat": "MAE" },
    { "expr": "avg(v2_test_r2)", "legendFormat": "R2" },
    { "expr": "avg(v2_test_adj_r2)", "legendFormat": "ADJ. R2" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(training_cpu_usage_percent)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "training_memory_usage_bytes", "legendFormat": "Memory Usage" }
   ]
  }
 ]
}